### ISSUE TITLE
format table to be formatted to look like the table in the paper

### ISSUE THREAD

**Issue by xihang-chen** [OHDSI/CohortSymmetry#143]
hey @daniellenewby  would you mind sharing a few tables here please? So that we could immitate the existing tables

**Comment by daniellenewby** [comment]
Some examples @nmercadeb 


https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4690514/
![image](https://github.com/oxford-pharmacoepi/CohortSymmetry/assets/16097637/2d95ca3e-26ae-4bc7-9534-beceb77e575f)

Although this is a figure look at columns they show n numbers for marker and index and the asr etc
![image](https://github.com/oxford-pharmacoepi/CohortSymmetry/assets/16097637/9b8f0efd-c300-43c6-a155-d2b299800e88)

![image](https://github.com/oxford-pharmacoepi/CohortSymmetry/assets/16097637/61cda43d-81f2-43f9-91dc-38c208ec3759)
